#!/usr/bin/env python3
"""Render a simple top10 alert image from JSON input.

Usage:
  python3 scripts/render_alert_image.py <input_json> <output_png>
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def main() -> int:
  if len(sys.argv) != 3:
    print("Usage: render_alert_image.py <input_json> <output_png>", file=sys.stderr)
    return 1

  input_path = Path(sys.argv[1])
  output_path = Path(sys.argv[2])

  try:
    from PIL import Image, ImageDraw, ImageFont
  except Exception:
    print(
      "Pillow is not installed. Install with: pip install pillow",
      file=sys.stderr,
    )
    return 2

  payload = json.loads(input_path.read_text(encoding="utf-8"))
  title = str(payload.get("title", "Top 10 Alert"))
  subtitle = str(payload.get("subtitle", ""))
  rows = payload.get("rows", [])
  if not isinstance(rows, list):
    rows = []

  width = 1200
  row_height = 42
  header_height = 140
  footer_height = 48
  height = max(480, header_height + footer_height + (len(rows) * row_height) + 24)

  image = Image.new("RGB", (width, height), (11, 18, 32))
  draw = ImageDraw.Draw(image)

  try:
    title_font = ImageFont.truetype("Arial.ttf", 44)
    subtitle_font = ImageFont.truetype("Arial.ttf", 24)
    row_font = ImageFont.truetype("Arial.ttf", 24)
  except Exception:
    title_font = ImageFont.load_default()
    subtitle_font = ImageFont.load_default()
    row_font = ImageFont.load_default()

  draw.rectangle([(0, 0), (width, header_height)], fill=(20, 34, 61))
  draw.text((36, 28), title, fill=(240, 246, 255), font=title_font)
  draw.text((36, 86), subtitle, fill=(190, 205, 230), font=subtitle_font)

  y = header_height + 20
  for idx, row in enumerate(rows[:18], start=1):
    model = str(row.get("model", "unknown"))
    vendor = str(row.get("vendor", "")).strip()
    change_type = str(row.get("type", "moved")).upper()
    before = row.get("before")
    after = row.get("after")
    before_text = "-" if before is None else f"#{before}"
    after_text = "-" if after is None else f"#{after}"

    bg = (14, 24, 43) if idx % 2 else (17, 30, 52)
    draw.rectangle([(24, y - 6), (width - 24, y + row_height - 8)], fill=bg)

    label = f"{idx:02d}. {model}"
    if vendor:
      label += f" ({vendor})"
    label += f"  |  {change_type}  |  {before_text} -> {after_text}"
    draw.text((36, y), label, fill=(225, 235, 248), font=row_font)
    y += row_height

  draw.rectangle([(0, height - footer_height), (width, height)], fill=(20, 34, 61))
  draw.text((36, height - 34), "Generated by model-tracker alert renderer", fill=(176, 193, 220), font=subtitle_font)

  output_path.parent.mkdir(parents=True, exist_ok=True)
  image.save(output_path, format="PNG")
  return 0


if __name__ == "__main__":
  sys.exit(main())

